apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: gravix
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  api-key: {{ .Values.global.apiKey | b64enc | quote }}
  s3-access-key: {{ .Values.global.storage.accessKey | b64enc | quote }}
  s3-secret-key: {{ .Values.global.storage.secretKey | b64enc | quote }}
  {{- if .Values.global.cubeApiSecret }}
  cube-api-secret: {{ .Values.global.cubeApiSecret | b64enc | quote }}
  {{- end }}
