global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ingestion"
    static_configs:
      - targets: ["ingestion:8080"]

  - job_name: "rollup"
    static_configs:
      - targets: ["host.docker.internal:9091"]
